DROP ROLE IF EXISTS ${APP_USER};

CREATE ROLE ${APP_USER} WITH LOGIN PASSWORD '${APP_PASSWORD}';

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_USER};
GRANT USAGE ON SCHEMA public TO ${APP_USER};

GRANT SELECT ON reporte_libros_populares TO ${APP_USER};
GRANT SELECT ON reporte_usuarios_status TO ${APP_USER};
GRANT SELECT ON reporte_ranking_generos TO ${APP_USER};
GRANT SELECT ON reporte_prestamos_kpis TO ${APP_USER};
GRANT SELECT ON reporte_autores_metricas TO ${APP_USER};

REVOKE CREATE ON SCHEMA public FROM ${APP_USER};